version: '3.4'

services:
  atlantic.masterdata.api:
    image: ${DOCKER_REGISTRY-}masterdataapi
    build:
      context: .
      dockerfile: src/Services/MasterData/Atlantic.MasterData.API/Dockerfile
    volumes:
      - ./src/Services/MasterData/Atlantic.MasterData.API/Data/:/app/Data/
      
